# Generated by Django 4.1.5 on 2023-02-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
